// 1. FAÇA UM PROGRAMA QUE O USUÁRIO INFORME 3 VALORES, E RETORNE A SOMA DOS TRÊS

//2. FAÇA UM PROGRAMA QUE O USUÁRIO INFORME TRÊS VALORES E RETORNE A MÉDIA

//3. FAÇA UM PROGRAMA QUE O USUÁRIO INFORME UM VALOR, E RETORNE A QUINTA PARTE DESTE VALOR

//4. FAÇA UM PROGRAMA QUE O USUÁRIO INFORME UM VALOR, E O RETORNO SEJA O QUADRADO DESSE NÚMERO

//5. FAÇA UM PROGRAMA QUE RECEBA DOIS NÚMEROS E RETORNE O MENOR NÚMERO

